// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebServer.Models;

#nullable disable

namespace WebServer.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241108044053_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebServer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Vendorcode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 195977.4f,
                            Quantity = 194,
                            Vendorcode = 7085620
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 142086.56f,
                            Quantity = 294,
                            Vendorcode = 8062596
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 199883.53f,
                            Quantity = 223,
                            Vendorcode = 5283477
                        },
                        new
                        {
                            Id = 4,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 186310.73f,
                            Quantity = 342,
                            Vendorcode = 7614644
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 124062.84f,
                            Quantity = 170,
                            Vendorcode = 2062152
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 139336.16f,
                            Quantity = 267,
                            Vendorcode = 1062017
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 175293.6f,
                            Quantity = 476,
                            Vendorcode = 7167541
                        },
                        new
                        {
                            Id = 8,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 176201.28f,
                            Quantity = 260,
                            Vendorcode = 5362800
                        },
                        new
                        {
                            Id = 9,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 123460f,
                            Quantity = 209,
                            Vendorcode = 5056715
                        },
                        new
                        {
                            Id = 10,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 131545.11f,
                            Quantity = 230,
                            Vendorcode = 6756049
                        },
                        new
                        {
                            Id = 11,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 170480.34f,
                            Quantity = 178,
                            Vendorcode = 1446214
                        },
                        new
                        {
                            Id = 12,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 105373.02f,
                            Quantity = 312,
                            Vendorcode = 8373948
                        },
                        new
                        {
                            Id = 13,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 167475f,
                            Quantity = 356,
                            Vendorcode = 9059606
                        },
                        new
                        {
                            Id = 14,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 134403.05f,
                            Quantity = 237,
                            Vendorcode = 1152479
                        },
                        new
                        {
                            Id = 15,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 111919.984f,
                            Quantity = 369,
                            Vendorcode = 9239595
                        },
                        new
                        {
                            Id = 16,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 100576.07f,
                            Quantity = 232,
                            Vendorcode = 5924304
                        },
                        new
                        {
                            Id = 17,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 116529.766f,
                            Quantity = 305,
                            Vendorcode = 4274701
                        },
                        new
                        {
                            Id = 18,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 151642.31f,
                            Quantity = 275,
                            Vendorcode = 5523603
                        },
                        new
                        {
                            Id = 19,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 116536.59f,
                            Quantity = 60,
                            Vendorcode = 4989383
                        },
                        new
                        {
                            Id = 20,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 173847.55f,
                            Quantity = 237,
                            Vendorcode = 8314411
                        },
                        new
                        {
                            Id = 21,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 108579.92f,
                            Quantity = 393,
                            Vendorcode = 5018855
                        },
                        new
                        {
                            Id = 22,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 152052.12f,
                            Quantity = 217,
                            Vendorcode = 7451374
                        },
                        new
                        {
                            Id = 23,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 164904.73f,
                            Quantity = 196,
                            Vendorcode = 7166602
                        },
                        new
                        {
                            Id = 24,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 182402.61f,
                            Quantity = 137,
                            Vendorcode = 2794390
                        },
                        new
                        {
                            Id = 25,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 193035.23f,
                            Quantity = 464,
                            Vendorcode = 8227786
                        },
                        new
                        {
                            Id = 26,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 141730.08f,
                            Quantity = 15,
                            Vendorcode = 6480433
                        },
                        new
                        {
                            Id = 27,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 156948.69f,
                            Quantity = 30,
                            Vendorcode = 4170937
                        },
                        new
                        {
                            Id = 28,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 191243.19f,
                            Quantity = 255,
                            Vendorcode = 3347152
                        },
                        new
                        {
                            Id = 29,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 108193.01f,
                            Quantity = 41,
                            Vendorcode = 7753437
                        },
                        new
                        {
                            Id = 30,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 169651.6f,
                            Quantity = 276,
                            Vendorcode = 3025148
                        },
                        new
                        {
                            Id = 31,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 137812.75f,
                            Quantity = 92,
                            Vendorcode = 9840367
                        },
                        new
                        {
                            Id = 32,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 132819.03f,
                            Quantity = 401,
                            Vendorcode = 2125720
                        },
                        new
                        {
                            Id = 33,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 113757.09f,
                            Quantity = 87,
                            Vendorcode = 4713380
                        },
                        new
                        {
                            Id = 34,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 164680.19f,
                            Quantity = 85,
                            Vendorcode = 3997063
                        },
                        new
                        {
                            Id = 35,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 199362.78f,
                            Quantity = 5,
                            Vendorcode = 8641694
                        },
                        new
                        {
                            Id = 36,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 174043.4f,
                            Quantity = 380,
                            Vendorcode = 7161461
                        },
                        new
                        {
                            Id = 37,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 104657.74f,
                            Quantity = 287,
                            Vendorcode = 5335127
                        },
                        new
                        {
                            Id = 38,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 186281.9f,
                            Quantity = 434,
                            Vendorcode = 4418221
                        },
                        new
                        {
                            Id = 39,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 189860.3f,
                            Quantity = 385,
                            Vendorcode = 3548451
                        },
                        new
                        {
                            Id = 40,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 104188.65f,
                            Quantity = 461,
                            Vendorcode = 4774645
                        },
                        new
                        {
                            Id = 41,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 147836.19f,
                            Quantity = 216,
                            Vendorcode = 5065993
                        },
                        new
                        {
                            Id = 42,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 122633.82f,
                            Quantity = 64,
                            Vendorcode = 3246486
                        },
                        new
                        {
                            Id = 43,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 192215.78f,
                            Quantity = 315,
                            Vendorcode = 6430590
                        },
                        new
                        {
                            Id = 44,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 182436.4f,
                            Quantity = 301,
                            Vendorcode = 5855319
                        },
                        new
                        {
                            Id = 45,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 174904.31f,
                            Quantity = 449,
                            Vendorcode = 4682938
                        },
                        new
                        {
                            Id = 46,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 176413.16f,
                            Quantity = 174,
                            Vendorcode = 8081579
                        },
                        new
                        {
                            Id = 47,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 131312.8f,
                            Quantity = 205,
                            Vendorcode = 6091373
                        },
                        new
                        {
                            Id = 48,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 112282.2f,
                            Quantity = 401,
                            Vendorcode = 1883531
                        },
                        new
                        {
                            Id = 49,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 155782.9f,
                            Quantity = 36,
                            Vendorcode = 2744963
                        },
                        new
                        {
                            Id = 50,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convallis. Donec ornare lacus sed elit viverra, sed sodales nulla gravida. Praesent malesuada velit arcu, non fermentum diam sollicitudin et. Fusce lobortis neque id porta porta. Nulla posuere risus ac faucibus fringilla. Vestibulum ultricies cursus interdum. Donec pharetra nunc tincidunt, consectetur nunc id, pharetra est. Duis sed tincidunt libero. Integer ut egestas nunc. Nullam commodo accumsan ante.",
                            Name = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum vehicula lectus ut convalli",
                            Price = 189300.02f,
                            Quantity = 333,
                            Vendorcode = 1999883
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
